
<!-- *************************************************************************** -->
<!-- ************************ASSESSMENT DESCRIPTION***************************** -->
<!-- *************************************************************************** -->
#Assessment Model

##Summary of Previous Assessments and Reviews

###History of Modeling Approaches Used for This Stock

Early stock assessments only assessed `r spp` in the combined U.S.-Vancouver and Columbia INPFC areas, i.e., `r spp` in these areas were treated as a unit stock, using time series of data that began during the 1970s [@demory_progress_1984; @turnock_status_1993]. The first assessment used stock reduction analysis and the second assessment used the length-based Stock Synthesis model. The third `r spp` assessment utilized the hybrid length-and-age-based Stock Synthesis 1 model, using data from 1977-1998 [@sampson_assessment_1999]. During the 1999 stock assessment an attempt was made to include separate area assessments for the Eureka and Monterey INPFC areas but acceptable models could not be configured due to a lack of data [@sampson_assessment_1999].

The 2005 `r spp` assessment was conducted as two separate stocks, the northern stock encompassing the U.S. Vancouver and Columbia INPFC areas and the southern stock including the Eureka, Monterey and Conception INPFC areas, using Stock Synthesis 2, a length-age structured model. Both the northern- and southern-area models specified the fishing year as beginning on November 1 and continuing through October 31 of the following year, with a November-February winter fishery and a March-October summer fishery. Landings prior to 1957 were assumed to have been taken during the summer season in years where monthly data were not available to split the catches seasonally. The complete catch history was reconstructed for `r spp` for the 2005 stock assessment, with the northern area model starting in 1910 and the southern area model in 1876. In 2005, the STAR panel noted that the `r spp` stock trends were similar in both northern and southern areas, in spite of the different modeling choices made for each area, and that a single coast-wide assessment should be considered. 

The 2009 and 2011 assessments treated `r spp` as a single coast-wide stock, with the fleets and landings structured by state (WA, OR, CA) area of catch. During the 2011 STAR panel concerns were raised regarding the difficulty of discriminating landings from Washington and Oregon waters, particularly in light of the Oregon historical landings reconstruction that includes a summary of data by port of landing but not by catch area, due to the fact that the Oregon and Washington vessels commonly fish in each other's waters and land in each other's ports. The availability of the historical comprehensive landings reconstruction for Oregon by port of landing lead the STAR panel to recommend combining the Washington and Oregon fleets within the coast-wide stock assessment using port of landing rather than catch area. 

Starting with the 2013 stock assessment, the coast-wide stock assessment now summarizes `r spp` landings by the port of landing and combines Washington and Oregon into a single fleet [@haltuch_status_2013]. This update assessment assumes the same approach as the 2013 stock assessment.

###Most Recent STAR Panel Recommendations
The most recent STAR panel for petrale sole was for the 2013 full assessment.  For clarity the petrale sole specific recommendations from the STAR panel are presented here, but given that this was an update assessment which limits model changes, these items have not been formally addressed.

\begin{enumerate}

\item The states of California and Oregon have completed comprehensive historical catch reconstructions. Washington historical data are not yet available. Completion of Washington historical catch reconstruction would provide a better catch series.

\item Update both the maturity and fecundity relationships using samples with wider geographic coverage to include California, and from more recent years for petrale sole would be beneficial. 

\item Studies on stock structure and movement of petrale sole indicating transboundary movement of petrale sole between U.S. and Canadian waters, particularly with regard to the winter-summer spawning migration. It will be informative to include a time-series plot of fishery catch from Canadian waters in future assessment.

\item Increased collection of commercial fishery age data as well as re-aging any available historical samples from California would help reduce uncertainty. While some recent age data were made available from California, sample sizes could be increased and this data collection needs to continue into the future. Without good age data, the ability to estimate year-class strength and the extent of variation in recruitment is compromised.

\item Where possible, historical otolith samples aged using a combination of surface and break-and-burn methods should be re-aged using the break-and-burn method. Early surface read otoliths should also be re-aged using the break and burn method. Historical otoliths aged with a standard method will allow the further evaluation of the potential impacts of consistent under-aging using surface read methods, changes in selectivity during early periods without any composition information, and potential changes in growth.

\item The effect of the implementation of the IFQ (catch shares) program that began during 2011 on fleet behavior, including impacts on discards, fishery selectivity, and fishing locations, would benefit from further study.

\item The extent of spatial variability on productivity processes such as growth, recruitment, and maturity is currently unknown and would benefit from further research. 

\item The Panel appreciated the delta-GLMM approach to derive an index of stock size from commercial CPUE data. However, there may still be factors other than stock size that affect time-trends in the standardized CPUE indices. The panel recommends:
\begin{enumerate}

\item Investigate using effort as an offset in the model. That is, rather than modeling catch/effort = effects, use catch = effort*effects. When a log-link is used then
log(effort) can be included as an additive offset, and most GLMM packages include this option. The advantage of this approach is that it is easy to investigate if catch is proportional to effort or not. For example, it may be that CPUE can be higher when effort is low than when effort is high.

\item Include further consideration of the impacts of trip limits on CPUE. Such limits were gradually introduced since 2006 in the winter fisheries and this may impact CPUE. This consideration should involve consultations with fleet members to understand how their fishing behavior was affected by trip limits.

\end{enumerate}

\end{enumerate}

###Response to Groundfish Subcommittee Requests
The 2019 Groundfish Subcommittee meeting was held in Seattle, Washington on August 22-23, 2019.  There were no formal requests made during the meeting.


##Model Structure and Assumptions


###Changes Between the 2013, the 2015 Update, and the Current Update Assessment Model
This update assessment model retains all parameterization assumed in the 2013 assessment. The only changes between the 2013 and this update assessment were extending and reprocessing data sources. This section linking the two models is intended to clearly identify where substantive changes were made. These changes include:

\begin{enumerate}

\item Fitting using SS v.3.30.13.

\item Added commercial fishery catch data (2015-2018).

\item Added composition data from the commercial fishery (length and age data 2015-2018) and reprocessed all data and expanded based upon the current methods.

\item Added recent discard data (2014-2017) and reprocessed all discard rate, average weight, and length composition data.

\item Added 2015-2018 `r nwfsc`  data and calculated the index of abundance using VAST.

\item Added `r nwfsc` length and age data 2015-2018.

\item `r tri` early and late indices of abundance were calculated using VAST.

\item Model tuning to re-weight data. 

\item Length-weight relationship parameters estimated outside of the stock assessment model from the `r nwfsc` data up to 2018 and input as fixed values.

\item Update the natural mortality prior for female and male fish.

\end{enumerate}

The general model set-up is described in Table \ref{tab:Model_setup}.

###Modeling Platform and Bridging Analysis
Stock Synthesis version 3.30.03.13 was used to estimate the parameters in the model [@methot_stock_2013]. r4ss, version 1.35.1, along with R version 3.4.3 were used to investigate and plot model fits. The exploration of models began by bridging from the 2015 update assessment to Stock Synthesis version 3.30.03.13, which produced no discernible difference (Figure \ref{fig:bridge}). A more detailed analysis of changes from the 2015 update assessment are shown in the [Added Data Analysis Section](#added_data).


###Summary of Fleets and Areas
Fishery removals were divided among 4 fleets: 1) Winter North trawl, 2) Summer North trawl, 3) Winter South trawl, and 4) Summer South trawl. Landings for the North fleet are defined as fish landed in Washington and Oregon ports. Landings for the South fleet are defined as fish landed in California ports. Removals by other gears are very small and are included in the trawl fishery removals. The data available for each fleet are described in Figure \ref{fig:data_plot}.


###Priors
Priors were applied only to parameters for steepness ($h$) and natural mortality ($M$). The steepness prior is based on the Myers [-@myers_maximum_1999] meta-analysis of flatfish steepness and the natural mortality prior is based on a meta-analysis completed by Hamel [-@hamel_method_2015]. The prior for steepness assumed a beta distribution with a mean equal to 0.80 (Figure \ref{fig:h_prior}). 

The natural mortality prior was updated for this update assessment using the Hamel meta-analysis approach. Maximum age was assumed to be 32 and 29 years for females and male, respectively (Figure \ref{fig:m_prior}). The same maximum age assumption was applied in the 2013 assessment. 


###Data Weighting
Length and conditional-age-at-length compositions from the `r nwfsc` were fit along with length and marginal age compositions from the fishery fleets and the `r tri`. Length data started with a input sample size determined from the approaches described in the [NWFSC West Coast Groundfish Bottom Trawl Survey](#nwfsc_survey) and [Fishery Length and Age Data](#fishery_data) Sections. It was assumed for conditional-age-at-length data that each age was a random sample within the length bin and the model started with a sample size equal to the number of fish in that length bin. 

The update assessment model was weighted using the McAllister and Ianelli [-@mcallister_bayesian_1997] method (Harmonic Mean weighting), consistent with the 2013 full and 2015 update assessments. The McAllister and Ianelli data weight approach looks at the difference between individual observations and predictions.  A sensitivity was performed examining the difference between alternative weighting approaches.  The weights applied to each length and age data set for the base model are shown in Table \ref{tab:harm}.

###Estimated and Fixed Parameters
There were `r mod1$N_estimated_parameters` estimated parameters in the base model. These included parameters for $R_0$, natural mortality by sex, steepness, growth, selectivity, retention, time blocking of the fleets and the surveys, commercial CPUE catchability, recruitment deviations, and forecast recruitment deviations (Table \ref{tab:model_params}).

Fixed parameters in the model were as follows. The standard deviation of the recruitment deviates was fixed at `r print(mod1$parameters[mod1$parameters$Label == "SR_sigmaR","Value"],2)`. Maturity-at-length and fecundity was fixed as described above in the [Maturitation and Fecundity](#mat_fecund) Section. Length-weight parameters were fixed at estimates using all length-weight observations (Figure \ref{fig:wt_length}).


###Key Assumptions and Structural Choices
All structural choices for stock assessment models are likely to be important under some circumstances. In this update assessment update these choices are generally made to be consistent with the previous assessment [@haltuch_status_2013]. Major choices in the structuring of this stock assessment model include a coast-wide model with seasonal fleet structure for two regions, north and south, splitting the `r tri` into an early and late time period, and estimates of selectivity and retention curves for each fleet.


<!-- ************************************************************************* -->
<!-- *********************BASE MODEL RESULTS********************************** -->
<!-- ************************************************************************* -->
##Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \ref{tab:model_params} and the likelihood components are shown in Table \ref{tab:like}. Estimates of derived reference points and approximate 95% asymptotic confidence intervals are shown in Table \ref{tab:Ref_pts}. Estimates of stock size over time are shown in Table \ref{tab:Timeseries_mod1}. 

###Parameter Estimates
Natural mortality by sex was estimated directly within the model.  Natural mortality was estimated to be `r round(mod1$parameters[mod1$parameters$Label == "NatM_p_1_Fem_GP_1", 3],3)` yr^-1^ for female fish and `r round(mod1$parameters[mod1$parameters$Label == "NatM_p_1_Mal_GP_1", 3],3)` yr^-1^ for male fish. In comparison the estimates from the 2015 assessment were 0.145 yr^-1^ and 0.154 yr^-1^ for female and male fish, respectively.  

Steepness was also estimated within the model, consistent with the approach applied in the 2013 full and 2015 update assessment. The estimate of steepness from the Beverton-Holt stock recruitment curve was estimated at `r print(mod1$parameters[mod1$parameters$Label == "SR_BH_steep","Value"],2)`. The previous update assessment estimated a steepness of 0.89.  

The estimates of maximum length and the von Bertanlaffy growth coefficient, $k$, were less than the external estimates for males and female but were well within the 95% confidence interval given the estimated uncertainty (Table \ref{tab:model_params}). The estimated $k$ for female and male fish were greater than the values estimated in the 2015 update assessment (`r round(mod1$parameters[mod1$parameters$Label == "VonBert_K_Fem_GP_1", 3],3)` versus 0.134 yr^-1^ for females and `r round(mod1$parameters[mod1$parameters$Label == "VonBert_K_Mal_GP_1", 3],3)` versus 0.203 yr^-1^ for males).  The majority of growth for female and male `r spp` growth occurs at younger ages, reaching near maximum length by age 10-15, depending upon sex, with female `r spp` reaching  larger maximum lengths (Figure \ref{fig:sizeatage}). The spawning output estimated was equal to the spawning weight of female fish (Figure \ref{fig:spawnoutlen}).

Selectivity curves were estimated for the fishery and survey fleets.  The estimated selectivities for the fishery fleets are shown in Figure \ref{fig:fish_selex}.  All fishery and survey selectivities were fixed to be asymptotic, reaching maximum selectivity for fish between 35 and 40 cm.  Shifts in selectivities for each fleet fishery were estimated based on time blocks assumed in the 2013 assessment (Figure \ref{fig:fish_selex}).  The estimated retention curves for each fleet based on the historical time blocks and discarded length composition data are shown in Figure \ref{fig:fish_reten}.  Sex specific survey selectivities were assumed to be asymptotic and are shown in Figure \ref{fig:survey_selex}.

The catchability for each of the winter CPUE time series were estimated as power functions. The Winter North base catchability value was estimated at `r round(exp(mod1$parameters[mod1$parameters$Label == "LnQ_base_WinterN(1)", 3]), 3)` with the exponent parameter at `r round(mod1$parameters[mod1$parameters$Label == "Q_power_WinterN(1)", 3], 3)`.  The Winter South base catchability value was estimated at `r round(exp(mod1$parameters[mod1$parameters$Label == "LnQ_base_WinterS(3)", 3]), 3)` with the exponent parameter at `r round(mod1$parameters[mod1$parameters$Label == "Q_power_WinterS(3)", 3], 3)`. 

The catchability for both surveys, `r tri` and `r nwfsc`, were analytically solved comparing observed to expected vulnerable biomass across all years.  The `r tri` had catchability values of `r round(exp(mod1$parameters[mod1$parameters$Label == "LnQ_base_TriEarly(5)", 3]), 3)` and `r round(exp(mod1$parameters[mod1$parameters$Label == "LnQ_base_TriLate(6)", 3]), 3)` for the early and late periods, respectively.  The `r nwfsc` catchability value `r round(exp(mod1$parameters[mod1$parameters$Label == "LnQ_base_NWFSC(7)", 3]), 3)`.

Additional survey variability, process error added directly to each year's input variability for the `r tri`, both early and late, was estimated within the model.  The model estimated an added variance of `r round(mod1$parameters[mod1$parameters$Label == "Q_extraSD_TriEarly(5)", 3], 3)` for the early time period of  and `r round(mod1$parameters[mod1$parameters$Label == "Q_extraSD_TriLate(6)", 3], 3)` for the late period. No additional variance was estimated for the `r nwfsc`. 

The time-series of estimated recruitments shows a relationship with the decline in spawning output, punctuated by larger recruitments  in recent years (2006, 2007, and 2008) (Figures \ref{fig:recruits} and \ref{fig:recdevs}). There is little information regarding recruitment prior to 1960 and the uncertainty in those estimates is expressed in the model. The five largest estimated recruitment estimated with the model (in ascending order) occurred in `r recdev.highest[1]`, `r recdev.highest[2]`, `r recdev.highest[3]`, `r recdev.highest[4]`, and  `r recdev.highest[5]`. The four lowest recruitments estimated within the model (in ascending order) occurred in `r recdev.lowest[1]`, `r recdev.lowest[2]`, `r recdev.lowest[3]`, and `r recdev.lowest[4]`. However, recruitment in recent years (2013 - 2017) is estimated to be less than the expected mean recruitment indicating an absence of strong incoming recruitment. The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias_adjust}.


###Fits to the Data
There are numerous types of data for which the fits are discussed: fishery CPUE, survey abundance indices, discard data (rates, mean body weights, and length compositions), length-composition data for the fisheries and surveys, marginal age compositions for the fisheries, and conditional age-at-length observations for the `r nwfsc`.

The fit to the CPUE for the winter fisheries is show in Figures \ref{fig:fit_wn_cpue}, \ref{fig:q_north}, \ref{fig:fit_ws_cpue}, and \ref{fig:q_south}. The model fits both of the CPUE time-series relatively well. The fits to the survey indices are shown in Figures \ref{fig:fit_tri_early}, \ref{fig:fit_tri_late}, and \ref{fig:fit_nwfsc_survey}.  In order to fit the early and the late periods of the `r tri` extra standard error was required. The trend in the early time-series of the `r tri` was generally not consistent with other data within the model. The final year, 2004, in the late period of the `r tri` was under fit by the model. The `r spp` survey index from the `r nwfsc` was generally fit well. However, the most recent year, 2018 data point which was lower than previous year's indices, was not fit by the model.   

The observed WCGOP discard rates (Figures \ref{fig:fit_wn_discard} - \ref{fig:fit_ss_discard}) were fit by each fishery using time blocks. The time blocks on the discard data were based on those defined in the 2013 assessment [@haltuch_california_2013] with the final block starting in 2011 being extended through the final model year, 2018. The discard rates for the northern fleets from the Pikitch data collected in 1985-1987 fit the mean of the estimates for the winter fishery (Figure \ref{fig:fit_wn_discard}) but estimated higher discard rates for the summer fleet (Figure \ref{fig:fit_sn_discard}).  The lack of fit to the summer fleet is consistent to the estimates from the 2015 update assessment.  Fits to the WCGOP observed mean body weights are shown in Figures \ref{fig:nw_bodywt_fit} - \ref{fig:ss_bodywt_fit}. The fits to the discard mean body weights to the summer fleets were generally better than the data from the winter fisheries which had more variable observations and lower number of observations (hence larger annual uncertainties). 

Fits to the length data are shown based on the proportions of lengths observed by year and the Pearson residuals-at-length for all fleets. Detailed fits to the length data by year and fleet are provided in [Appendix A](#append_a).  Aggregate fits by fleet are shown in Figure \ref{fig:length_agg}.  There are a few things that stand out when examining the aggregated length composition data. First, the sexed discard lengths from the Pikitch study appear to be poorly fit by the model but this is related to small sample sizes.  However, the unsexed discard lengths from the WCGOP data for each fleet were fit well by the model. 

Discard lengths from WCGOP were fit well by the model and show no obvious pattern in the residuals (Figures \ref{fig:discard_wn_len_pearson} - \ref{fig:discard_ss_len_pearson}).  The residuals to the fishery lengths clearly showed the growth differential between males and females where the majority of positive residuals at larger sizes were from female fish (Figures \ref{fig:wn_len_pearson} - \ref{fig:ss_len_pearson}). Notably, the Summer North fishery has a large positive residual pattern for male fish between 1966-1980. A similar pattern in the Pearson residuals was observed in the 2013 full and the 2015 update assessment [@haltuch_status_2013; @stawitz_stock_2015]. The residuals for each of the surveys are shown in Figures \ref{fig:tri_early_len_pearson}, \ref{fig:tri_late_len_pearson}, and  \ref{fig:nwfsc_combo_len_pearson}. The Pearson residuals from the `r nwfsc` shows indications of the 2008 cohort moving through the population. Length data were weighted according to the McAllister Ianelli Harmonic approach and the data weights are shown in Table \ref{tab:harm}.

Age data were fitted to as marginal age compositions for the fishery fleets.The `r nwfsc` ages were treated as conditional age-at-length data to facilitate the estimation of growth within the model.  The aggregated fits to the marginal age data are shown in Figure \ref{fig:age_agg}.  The aggregated age data were fit generally well for the fishery fleets, however, the peaks of the age data were often under fit by the model which was also observed in the 2013 assessment [@haltuch_status_2013].  Detailed fits to the age data by year and fleet are provided in [Appendix B](#append_b). The Pearson residuals for the fishery fleets are shown in Figures \ref{fig:wn_age_pearson} - \ref{fig:ss_age_pearson}. The age data were weighted using the McAllister Ianelli approach and the data weights are shown in Table \ref{tab:harm}.  

The observed and expected conditional age-at-length fits for `r nwfsc` are shown in Figures \ref{fig:nwfsc_combo_andre_1} - \ref{fig:nwfsc_combo_andre_6}. The fits generally match the observations. The Pearson residuals are shown in Figure \ref{fig:nwfsc_combo_pearson_1} and \ref{fig:nwfsc_combo_pearson_2}.  The age data were also weighted according to the McAllister Ianelli Harmonic mean weights (Table \ref{tab:harm}). 

###Population Trajectory
The predicted spawning biomass is given in Table \ref{tab:Timeseries_mod1} and plotted in Figure \ref{fig:ssb}. The predicted spawning biomass time series shows a strong decline from the late-1930s through the mid-1960s, followed by a small recovery through the mid-1970s, and another decline to its lowest point during the early 1990s.  This general pattern of stock decline is coincident with increasing catches and the movement of the fishery from the south to the north, and from summer fishing in shallow waters to winter fishing on spawning aggregations in deeper waters. From the mid-1990s through 2005 the stock increased slightly, then declined through 2010 (Figure \ref{fig:ssb}). The stock has increased strongly since 2010 in response to reduced catches and above average recruitment in 2006, 2007, and 2008. The estimated total biomass follows the same general trend as observed in the spawning biomass (Figure \ref{fig:total_bio}). The `r LastYR` estimated spawning biomass relative to unfished equilibrium spawning biomass is above the target of 25% of unfished spawning biomass at `r Depl_mod1` (Figure \ref{fig:depl}). Approximate confidence intervals based on the asymptotic variance estimates show that the uncertainty in the estimated spawning biomass is generally low. The standard deviation of the log of the spawning biomass in `r LastYR` is `r round(mod1$Pstar_sigma,2)`.

Recruitment deviations were estimated for the entire time-series that was modeled (Figure \ref{fig:recruits} and discussed in Section \ref{parameter-estimates}) and provide a realistic portrayal of uncertainty. The time series of estimated recruitments shows a relationship with the decline in spawning output, punctuated by larger recruitments in 2006, 2007, and 2008. The five largest recruitments estimated by the model (in ascending order) occurred in `r recdev.highest[1]`, `r recdev.highest[2]`, `r recdev.highest[3]`, `r recdev.highest[4]`, and  `r recdev.highest[5]`. The four lowest recruitments estimated within the model (in ascending order) occurred in `r recdev.lowest[1]`, `r recdev.lowest[2]`, `r recdev.lowest[3]`, and `r recdev.lowest[4]`. However, in recent years, 2013 - 2016, based on the data the incoming recruitment has been estimated to be lower than average with negative recruitment deviations (ranging between -0.10 and -0.33) indicating an absence of strong incoming recruitment.  

The stock-recruit curve resulting from a value of estimated steepness, `r print(mod1$parameters[mod1$parameters$Label == "SR_BH_steep","Value"],2)`, is shown in Figure \ref{fig:stock_recruit_curve} with estimated recruitments also shown. 

###Reference Points
Reference points were calculated using the estimated selectivities and catch distributions among fleets in the most recent year of the model (`r LastYR - 1`). Sustainable total yields (landings plus discards) were `r prettyNum(Ref_pts_mod1[15,2],big.mark = ",")` mt when using an $SPR_{30\%}$ reference harvest rate and with a 95% confidence interval of `r prettyNum(Ref_pts_mod1[15,3],big.mark = ",")` mt based on estimates of uncertainty. The spawning biomass equivalent to 25% of the unfished spawning output ($SB_{25\%}$) was `r prettyNum(Ref_pts_mod1[7,2],big.mark = ",")`. 

The predicted spawning biomass from the base model generally showed a decline beginning during the 1950s and reaching a low in spawning biomass in `r low.ssb` with the stock declining to `r low.dep.value` relative stock size (Figures \ref{fig:ssb} and \ref{fig:depl}). Since 2010, the spawning biomass has been increasing due to small catches and above average recruitment. The `r LastYR` spawning biomass relative to unfished equilibrium spawning biomass is above the target of 25% of unfished (Figure \ref{fig:depl}). The fishing intensity, 1-SPR, exceeded the current  harvest rate limit ($SPR_{30\%}$) throughout the late 1970s until approximately 2010 as seen in Figure \ref{fig:SPR_all_fig}. Recent exploitation rates on `r spp` were estimated to be less than target levels. 

Table \ref{tab:Ref_pts} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value estimated at `r print(mod1$parameters[mod1$parameters$Label == "SR_BH_steep","Value"],2)`.


## Modeling Diagnostics

###Convergence
Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered by 5% and 10%. This was repeated 50 times and a better minimum was not found (Table \ref{tab:jitter}). Jittering showed the model to be sensitive to starting values and there were a number of times where the model resulted in similar likelihood values (< 1 unit difference) to the maximum likelihood estimate.  This is likely due to the high correlation between some parameters in the model (i.e., natural mortality and steepness) which allow the model to find similar fits to the data that result in similar estimates. 

Through the jittering done as explained above and likelihood profiles, we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian.  


###Sensitivity Analyses
A number of sensitivity analyses were conducted.  Each of the sensitivities conducted was a single exploration from the base model assumptions and/or data, and were not performed in a cumulative fashion.

\begin{enumerate}

  \item Fix natural mortality value for female fish at a lower value of 0.125.
  
  \item Fix natural mortality value for female fish at a higher value of 0.180.
  
  \item Use the natural mortality prior for female and male fish used in the 2015 update assessment, natural mortality estimated for both sexes.
  
  \item Use the coastwide fecundity relationship for `r spp` estimated by Lefebvre et al. in press.
  
  \item Estimate the sex ratio at birth between female and male fish within the model. Single parameter estimated for the modeled years.  Future explorations may want to explore blocking of this parameter for pre- and post-development of the spawning ground Winter fishery with the assumption that this may disproportionately impact the numbers of female `r spp`.
  
  \item Estimate the sex ratio at birth between female and male fish within the model and assume the coastwide fecundity relationship for `r spp` based on Lefebvre et al. in press. Single parameter for the sex ratio estimated across all modeled years. 
  
  \item Data weighting according to the Francis method using the weighting values shown in Table \ref{tab:francis}. 
  
  \item Data weighting according to the Dirichlet method where the estimated parameters are shown in Table \ref{tab:dirichlet}. 
  
\end{enumerate}

Likelihood values and estimates of key parameters from each sensitivity are available in Table \ref{tab:sens_table}.  Plots of the estimated time-series of spawning biomass and relative spawning biomass are shown in Figures \ref{fig:sens_ssb} and \ref{fig:sens_depl}.

The two sensitivities exploring higher and lower natural mortality for female `r spp` were the two sensitivities that differed the most from the base model.  The estimated spawning biomasses and relative stock statuses were higher or lower compared to the base model for each of these runs (Table \ref{tab:sens_table}, Figures \ref{fig:sens_ssb} and \ref{fig:sens_depl}).  

Two sensitivities exploring alternative data weighting approaches were compared to the base model which was weighted using the McAllister-Ianelli data weighting approach.  Both data weighting approaches resulted in similar estimates to the base model (Table \ref{tab:francis} and Figures \ref{fig:sens_ssb} and \ref{fig:sens_depl}). However, the Dirichlet data weighting approach which estimates a parameter for each data source (e.g., length by fleet and ages by fleet), the estimated parameters hit the upper bounds for each data source (Table \ref{tab:dirichlet}). Converted to real space, this data weighting approach resulted in full weight (approximately 1) for each data set.  The Dirichlet method is restricted to data weights less than one, but both the Francis and McAllister and Ianelli approaches estimated data weights greater than one for some data sets. The estimated data weights are linked to the calculation of the input sample sizes which in this model were calculated based on the number of trips for the commercial data and a combination on number of tows and fish samples for the surveys. Future work should be done to better understand the performance of data weighting approaches dependent upon the calculation of input sample sizes.  

The final sensitivities that had potentially meaningful differences from the base model were the three runs that explored a skewed sex ratio, potential changes in the fecundity relationship for female `r spp`, and both of these items combined. Each of these sensitivities resulted in slightly more pessimistic estimates of the relative spawning biomass (Table \ref{tab:sens_table}).  It would be expected that the next full assessment would explore both of these parameter changes.    

###Retrospective Analysis
A five-year retrospective analysis was conducted by running the model using data only through 2013, 2014, 2015, 2016, 2017 and 2018 (Figures \ref{fig:retro_ssb}, \ref{fig:retro_depl}, and \ref{fig:retro_recdev}). The initial scale of the spawning biomass trended upward relative to the base model. Overall, no alarming patterns were present in the retrospective analysis.  

###Added Data Analysis {#added_data}
The changes from the 2015 update assessment based on the addition and reprocessing of data was explored.  Each data source was added starting with catches and ending with ages for all fleets within the model where each model run contains the earlier updated data (e.g., + Lengths has data through 2019 for the catches, indices, discard rates and weights, and lengths for all fleets with only the age data through 2014).  The estimates of the spawning biomass, relative spawning biomass, and the annual recruitment deviations from each model are shown in Table \ref{tab:bridge_table} and Figures \ref{fig:ssb_data}, \ref{fig:depl_data}, and \ref{fig:recdev_data}.

The time-series when data was added was relatively similar to the estimates from the 2015 update assessment.  The one notable difference is the estimates of spawning biomass between the 1950s and 1970s.  This update assessment estimates marginally larger spawning biomasses during this period relative to the 2015 estimate.  The source of this change was due to two changes; 1) the removal of non-random samples from Oregon from the commercial biological data contained in PacFIN (see [Fishery Length and Age Data Section](#fishery_data) for additional information), and 2) improvements in the processing and expansion of PacFIN data.  

###Historical Analysis
The estimated summary biomass from previous assessments since 2005 are shown in Figure \ref{fig:historical_analysis}.  The current assessment estimated a slight increase in initial spawning biomass compared to previous assessments.  

###Likelihood Profiles
Likelihood profiles were conducted for $R_0$, steepness, and female natural mortality values separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimated the remaining parameters based on the fixed parameter value.

For steepness, the negative log-likelihood supported values between 0.70 - 0.95 (Figure \ref{fig:piner_h}).  Likelihood components by data source show that the  age data (primarily the Northern fleets) support a higher steepness value while the length data from the `r nwfsc` support lower values.  The surveys generally provide very little information concerning steepness. The relative spawning biomass for `r spp` diverges most during the middle of the time series based on the assumed values of steepness with the final status being above the management target biomass (Figures \ref{fig:h_ssb_trajectory} and \ref{fig:h_depl_trajectory}).

The negative log-likelihood was minimized at a female natural mortality value of `r round(mod1$parameters[mod1$parameters$Label == "NatM_p_1_Fem_GP_1", 3],3)`, but the 95% confidence interval extends over values ranging from 0.12 - 0.18.  Male natural mortality was estimated in the likelihood profile.  The age and length data likelihood contribution was minimized at female natural morality values ranging from 0.15-0.16 (Figure \ref{fig:m_like}).  The relative spawning biomass for `r spp` widely varied across alternative values of natural mortality (Figures \ref{fig:m_ssb_trajectory} and \ref{fig:m_depl_trajectory}).

In regards to values of $R_0$, the negative log-likelihood was minimized at approximately log($R_0$) of `r round(log(mod1$derived_quants[mod1$derived_quants$Label == "Recr_Virgin",2]),2)`  (Figure \ref{fig:piner_R0}).  The data source with the largest information regarding $R_0$ was the `r nwfsc`.


##Unresolved Problems and Major Uncertainties
Parameter uncertainty is explicitly captured in the asymptotic confidence intervals reported throughout this assessment for key parameters and management quantities. These intervals reflect the uncertainty in the model fit to the data sources included in the assessment, but do not include uncertainty associated with alternative model configurations, weighting of data sources (a combination of input sample sizes and relative weighting of likelihood components), or fixed parameters.

There are a number of major uncertainties regarding model parameters that have been explored via sensitivity analysis. The most notable explorations involved the sensitivity of model estimates to:

\begin{enumerate}

\item The stocks rapid increase in biomass since 2010 was driven by reduced catches and three strong year-classes, 2006-2008, entering the population.  In recent years, strong recruitments in a single year have been observed leading to sharp increases in biomass in other West Coast groundfish stocks. However, the observation of three subsequent strong recruitments has not been commonly observed in other stocks and the specific mechanisms that led to these three strong-year classes are currently unknown. 

\item The value of natural mortality by sex.	Natural mortality by sex and steepness are uncertain for `r spp`.  Currently, both natural mortality and steepness are estimated within the model and are negatively correlated.  This provides information regarding these parameters combined values, but there is large uncertainty regarding the value of each parameter individually.

\item New fecundity data for `r spp` supports a fecundity relationship that differs from the current assumption (fecundity equals body weights) in this update assessment. A sensitivity to the new data results in a less optimistic estimate of relative spawning biomass, declining to 35% from the base model 39%, when the new coast-wide fecundity relationship was included in the model. The new data supports differences in fecundity estimated between `r spp` observed in the north and south off the U.S. west coast.  However, some of the contrast in estimates between the northern and southern fish may be due to sample sizes differences. The next full assessment for `r spp` will want to explore methods of how best to include the new fecundity data. 

\item Additionally, a reconstructed historical Washington catch history has not been included in the `r spp` stock assessment.  Washington state is currently undergoing efforts to determine historical catches for `r spp` and the next stock assessment is likely to incorporate these new historical catch estimates. 

\end{enumerate}